<?xml version="1.0" encoding="utf-8"?>
<Project>
 <PropertyGroup>
     <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
     <EnablePackageVersionOverride>true</EnablePackageVersionOverride>
 </PropertyGroup>

 <ItemGroup>
     <PackageVersion Include="Avalonia" Version="12.0.5" />
     <PackageVersion Include="Avalonia.Desktop" Version="12.0.5" />
     <PackageVersion Include="Avalonia.Fonts.Inter" Version="12.0.5" />
     <PackageVersion Include="Avalonia.Themes.Fluent" Version="12.0.5" />
     <PackageVersion Include="Xaml.Behaviors.Avalonia" Version="12.0.0.1" />
 </ItemGroup>

 <ItemGroup>
     <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.2" />
     <PackageVersion Include="Microsoft.Extensions.FileProviders.Abstractions" Version="10.0.9" />     
     <PackageVersion Include="CodeSugar.IO.SourceGenerator" Version="1.0.0-Prv-20260618-124635" />
 </ItemGroup>
	
</Project>
